//
//  CalculaIMCWorker.swift
//  Calculadora de IMC
//
//  Created by user on 03/05/22.
//  Copyright (c) 2022 Angela Yu. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class CreateIMCWorker
{
    func floatToDouble(
        _ floatValue: Float,
        _ digits: Double
    ) -> Double
    {
        let convertedValue = Double(
            floatValue
        )
        let rounded = Double(
            round( digits * convertedValue ) / digits
        )
        
        return rounded
    }
}
