//
//  CalculaIMCPresenter.swift
//  Calculadora de IMC
//
//  Created by user on 03/05/22.
//  Copyright (c) 2022 Angela Yu. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CreateIMCPresentationLogic
{
    func presentWeight(
        response: CreateIMC.FormatWeight.Response
    )
    func presentHeight(
        response: CreateIMC.FormatHeight.Response
    )
}

class CreateIMCPresenter: CreateIMCPresentationLogic
{
    //MARK: - ATRIBUTES
    weak var viewController: CreateIMCDisplayLogic?
    
    // MARK: Do something
    func presentHeight(
        response: CreateIMC.FormatHeight.Response
    ) {
        let height = "\( response.height )m"
        let viewModel = CreateIMC.FormatHeight.ViewModel(
            height: height
        )
        viewController?.displayHeight(
            viewModel: viewModel
        )
    }
    func presentWeight(
        response: CreateIMC.FormatWeight.Response
    ) {
        let weight = "\( response.weight )kg"
        let viewModel = CreateIMC.FormatWeight.ViewModel(
            weight: weight
        )
        viewController?.displayWeight(
            viewModel: viewModel
        )
    }
}
