//
//  CalculaIMCInteractor.swift
//  Calculadora de IMC
//
//  Created by user on 03/05/22.
//  Copyright (c) 2022 Angela Yu. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CreateIMCBusinessLogic
{
    func formatWeight(
        request: CreateIMC.FormatWeight.Request
    )
    func formatHeight(
        request: CreateIMC.FormatHeight.Request
    )
}

protocol CreateIMCDataStore
{
    var imcToEdit: IMC? { get set }
}

class CreateIMCInteractor: CreateIMCBusinessLogic, CreateIMCDataStore
{
    var presenter: CreateIMCPresentationLogic?
    var worker: CreateIMCWorker?
    
    var imcToEdit: IMC?
    
    // MARK: Do something
    func formatHeight(
        request: CreateIMC.FormatHeight.Request
    ) {
        worker = CreateIMCWorker()
        if let height = worker?.floatToDouble(
            request.height, 10
        ){
            let response = CreateIMC.FormatHeight.Response(
                height: height
            )
            presenter?.presentHeight(
                response: response
            )
        }
    }
    func formatWeight(
        request: CreateIMC.FormatWeight.Request
    ) {
        worker = CreateIMCWorker()
        if let weight = worker?.floatToDouble(
            request.weight, 100
        ){
            let response = CreateIMC.FormatWeight.Response(
                weight: weight
            )
            presenter?.presentWeight(
                response: response
            )
        }
    }
    
}
