//
//  CalculaIMCModels.swift
//  Calculadora de IMC
//
//  Created by user on 03/05/22.
//  Copyright (c) 2022 Angela Yu. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum CreateIMC
{
    // MARK: Use cases
    enum Something
    {
        struct Request
        {
        }
        struct Response
        {
        }
        struct ViewModel
        {
        }
    }
    enum FormatWeight
    {
        struct Request
        {
            var weight: Float
        }
        struct Response
        {
            var weight: Double
        }
        struct ViewModel
        {
            var weight: String
        }
    }
    enum FormatHeight
    {
        struct Request
        {
            var height: Float
        }
        struct Response
        {
            var height: Double
        }
        struct ViewModel
        {
            var height: String
        }
    }
    
}
