//
//  MostraResultadoInteractor.swift
//  Calculadora de IMC
//
//  Created by user on 03/05/22.
//  Copyright (c) 2022 Angela Yu. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MostraResultadoBusinessLogic
{
  func doSomething(request: MostraResultado.Something.Request)
}

protocol MostraResultadoDataStore
{
  //var name: String { get set }
}

class MostraResultadoInteractor: MostraResultadoBusinessLogic, MostraResultadoDataStore
{
  var presenter: MostraResultadoPresentationLogic?
  var worker: MostraResultadoWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: MostraResultado.Something.Request)
  {
    worker = MostraResultadoWorker()
    worker?.doSomeWork()
    
    let response = MostraResultado.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
