//
//  CalculaIMCInteractor.swift
//  Calculadora de IMC
//
//  Created by user on 03/05/22.
//  Copyright (c) 2022 Angela Yu. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CalculaIMCBusinessLogic
{
  func doSomething(request: CalculaIMC.Something.Request)
}

protocol CalculaIMCDataStore
{
  //var name: String { get set }
}

class CalculaIMCInteractor: CalculaIMCBusinessLogic, CalculaIMCDataStore
{
  var presenter: CalculaIMCPresentationLogic?
  var worker: CalculaIMCWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: CalculaIMC.Something.Request)
  {
    worker = CalculaIMCWorker()
    worker?.doSomeWork()
    
    let response = CalculaIMC.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
