//
//  CalculaIMCPresenter.swift
//  Calculadora de IMC
//
//  Created by user on 03/05/22.
//  Copyright (c) 2022 Angela Yu. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CalculaIMCPresentationLogic
{
  func presentSomething(response: CalculaIMC.Something.Response)
}

class CalculaIMCPresenter: CalculaIMCPresentationLogic
{
  weak var viewController: CalculaIMCDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: CalculaIMC.Something.Response)
  {
    let viewModel = CalculaIMC.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
