//
//  ShowIMCPresenter.swift
//  Calculadora de IMC
//
//  Created by user on 04/05/22.
//  Copyright (c) 2022 Angela Yu. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ShowIMCPresentationLogic
{
  func presentSomething(response: ShowIMC.Something.Response)
}

class ShowIMCPresenter: ShowIMCPresentationLogic
{
  weak var viewController: ShowIMCDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: ShowIMC.Something.Response)
  {
    let viewModel = ShowIMC.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
