//
//  ShowIMCInteractor.swift
//  Calculadora de IMC
//
//  Created by user on 04/05/22.
//  Copyright (c) 2022 Angela Yu. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ShowIMCBusinessLogic
{
  func doSomething(request: ShowIMC.Something.Request)
}

protocol ShowIMCDataStore
{
  //var name: String { get set }
}

class ShowIMCInteractor: ShowIMCBusinessLogic, ShowIMCDataStore
{
  var presenter: ShowIMCPresentationLogic?
  var worker: ShowIMCWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: ShowIMC.Something.Request)
  {
    worker = ShowIMCWorker()
    worker?.doSomeWork()
    
    let response = ShowIMC.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
