//
//  ShowIMCWorker.swift
//  Calculadora de IMC
//
//  Created by user on 04/05/22.
//  Copyright (c) 2022 Angela Yu. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class ShowIMCWorker
{
  func doSomeWork()
  {
  }
}
